### ISSUE TITLE
Improve command execution

### ISSUE THREAD

**Issue by FZambia** [zhebrak/raftos#1]
Hi! It could be much more efficient if you get rid of timeout [here](https://github.com/zhebrak/raftos/blob/master/raftos/state.py#L252) using future and resolving right at moment you got majority of success responses from followers.

**Comment by zhebrak** [comment]
\+ [state.py:467](https://github.com/zhebrak/raftos/blob/master/raftos/state.py#L467)

**Comment by zhebrak** [comment]
Fixed in #3. Thanks!
