### ISSUE TITLE
Retrieving Replicated value on Follower node

### ISSUE THREAD

**Issue by avinash240** [zhebrak/raftos#15]
# on leader
counter = raftos.Replicated(name='counter')
await counter.set(42)

# on follower, how do I retrieve the value above
counter = raftos.Replicated(name='counter')
value = await counter.get() # errors outs saying it requires the node to be leader

**Comment by zhebrak** [comment]
The idea is that all data communication should be done from a Leader node. Followers are there to receive updates from the Leader and initiate an election if the Leader is down.

**Comment by avinash240** [comment]
That seems like a missed opportunity.  I understand only having the leader as a writer, but the protocol doesn't really have any limitations on multiple readers, i.e. etcd, Pysyncobj.  Are there any technical issues that prevent the get_value() on the state object from working on follower nodes?

**Comment by zhebrak** [comment]
Getting values from 2 different Followers may result in 2 different values :) There is no guarantee of any consistency, are you OK with this?

**Comment by avinash240** [comment]
Ah... So it doesn't have any logic to consider the value committed once
we've got a qourum among nodes for the write?

Marlon

**Comment by zhebrak** [comment]
Once the value is committed in the leader we are sure it'll still be committed if this leader fails and there will be a new one. Raft algorithm ensures consistency among all possible leaders.
