### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by johannesl** [zhebrak/raftos#8]
Hi Alexander!
Happy to have found your project - looks like a good start for using RAFT consensus in your Python projects. Do you have any plans for supporting Python 2.7 in the future?

**Comment by zhebrak** [comment]
Hi Johannes! raftos is using asyncio module that was introduced in Python 3 branch only. We can try to use Trollius but I don't see why do we need to support 2.7 in new projects :)

You can check out [PySyncObj](https://github.com/bakwc/PySyncObj) by @bakwc

**Comment by johannesl** [comment]
One reason could be integrating it into an existing Python 2 code base, which I'm considering here. Another reason could be that the future for Python 3 doesn't look all that bright.. Most developers in the industry that I know are still using Python 2 for their projects.

Thanks for the link!

**Comment by zhebrak** [comment]
There is no future for Python 2 whatsoever, it's not getting any development. So I believe building new projects in Python 3 and porting the older ones is the answer. Feel free to write me if you have any questions about the Raft itself though.
